version: '3.8'

services:
  api:
    build: .
    env_file:
      - .env
    environment:
      - HF_HOME=/root/.cache/huggingface
    ports:
      - "8000:80"
    volumes:
      - .:/app
      # Use bind mount to /scratch for Hugging Face cache (1.5TB available)
      - /scratch/huggingface_cache:/root/.cache/huggingface
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
